stages:
- build
- deploy
variables:
  DOCKERHUB: dockerhub.local
  VERSION: $CI_COMMIT_REF_SUG-$CI_PIPELINE_ID  
  SERVICE: filter-rivals
build:
  stage: build 
  script:
  - docker build . -t $DOCKERHUB/$SERVICE:$VERSION

deploy-to-prod:
  stage: deploy
  when: manual
  only:
  - tags
  script:
  - helm-deploy $SERVICE $VERSION ./k8s production     
      --set dockerImage=$DOCKERHUB/$SERVICE:$VERSION        


deploy-to-test:
  stage: deploy
  when: manual
  only:
  - tags
  script:
  - helm-deploy $SERVICE $VERSION ./k8s development     
      --set dockerImage=$DOCKERHUB/$SERVICE:$VERSION        