{{$web := required "webName is required" .Values.web}}
{{$dockerImage := required "dockerImage is required" .Values.dockerImage}}
{{$port := required "port is required" .Values.port}}
{{$resources := required "resources is required" .Values.resources}}
{{$envs := .Values.env}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-{{$web}}
spec:
  selector:
    matchLabels:
      app: web-{{$web}}
  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app: web-{{$web}}
    spec:
      containers:
      - image: {{$dockerImage}}
        name: web-{{$web}}
        {{if $envs }}
        env:
          {{ range $varName,$varVal := $envs }}
          - name: {{$varName}}
            value: {{$varVal}}
          {{ end }}
        {{end}}
        ports:
        - containerPort: {{$port}}
        resources:
          limits:
            cpu: {{required "resources.limits.cpu is required" $resources.limits.cpu}}
            memory: {{required "resources.limits.memory is required" $resources.limits.memory}}
          requests:
            cpu: {{required "resources.requests.cpu is required" $resources.requests.cpu}}
            memory: {{required "resources.requests is required" $resources.requests.memory}}