{{$pathes := required "Pathes is required" .Values.pathes}}
{{$web := required "webName is required" .Values.web}}
{{$port := required "port is required" .Values.port}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{$web}}
spec:
  rules:
  - host: {{$web}}.{{.Release.Namespace}}.k8s
    http:
      paths:
{{ range $k,$v := $pathes }}
    {{ $path := $v }}
    {{ if hasPrefix "=" $path }}
     {{ $path := trimAll "= " $path}}
      - path: {{$path}}
    {{else}}
      - path: {{$path}}
    {{ end }}    
        backend:
          serviceName: {{$web}}
          servicePort: 80
{{ end }}